### ISSUE TITLE
Custom bell sounds

### ISSUE THREAD

**Issue by fn-ix** [enormandeau/meditation-timer#13]
Give users the ability to set their preferred bell sound from the command line.

Additionally, more bell sounds could be included to give users a small selection to choose from. I've included a few high-quality sounds from different instruments. Note that some of them are very long (>30s), so in order for them to sound good, #11 would have to be implemented first.
[chimes.zip](https://github.com/enormandeau/meditation-timer/files/3488921/chimes.zip)

**Comment by enormandeau** [comment]
If you provide me with working code for #11 I'll see how I can add some sounds. I would potentially compress them some. I like having my repositories to remain very light. Adding 4.5 MB of mp3s is not in line with that philosophy. Besides, if you want to use different bells, you can just substitute the file in your local installation.

As an aside, I see how you may want to next ask that different bells could be specified at different moments during the meditation or any number of small changes.

The philosophy behind meditation-timer is to keep things simple; zen. I do not plan to add a lot more complexity.

If you want, the license (GPL 3.0) is permissive enough for you to fork the project and modify at your will.

**Comment by hfel** [comment]
Alright, I wasn't aware of that philosophy. Actually, I wasn't thinking of having different sounds for every strike, just allowing users to select the chime that they find most pleasant for themselves.

I've already replaced them in my case; I only submitted this issue as a possible enhancement. But it's not as big an improvement as the other requests I made and changing the sound file is also something most people can do themselves, so feel free to ignore it altogether. ;)

I would add though that it's better to either add the sounds in full quality or not at all, since they tend to be long and having a selection of several poor-quality bell imitations is not as good as one sound that sounds real in my opinion. :)
